// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbchain/msgs/msgs_limit_p2p.proto

package dbchain.msgs;

public final class MsgsLimitP2P {
  private MsgsLimitP2P() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgModifyP2PTransferLimitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.MsgModifyP2PTransferLimit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>bool limit = 2;</code>
     * @return The limit.
     */
    boolean getLimit();
  }
  /**
   * <pre>
   *&#47;/ MsgChangeP2PTransferLimit defines a  limit of transfer message
   *type MsgModifyP2PTransferLimit struct {
   *	Owner sdk.AccAddress `json:"owner"`
   *	Limit bool           `json:"limit"`
   *}
   * </pre>
   *
   * Protobuf type {@code dbchain.msgs.MsgModifyP2PTransferLimit}
   */
  public static final class MsgModifyP2PTransferLimit extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.MsgModifyP2PTransferLimit)
      MsgModifyP2PTransferLimitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgModifyP2PTransferLimit.newBuilder() to construct.
    private MsgModifyP2PTransferLimit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgModifyP2PTransferLimit() {
      owner_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgModifyP2PTransferLimit();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgModifyP2PTransferLimit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 16: {

              limit_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit.class, dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit.Builder.class);
    }

    public static final int OWNER_FIELD_NUMBER = 1;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIMIT_FIELD_NUMBER = 2;
    private boolean limit_;
    /**
     * <code>bool limit = 2;</code>
     * @return The limit.
     */
    @java.lang.Override
    public boolean getLimit() {
      return limit_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, owner_);
      }
      if (limit_ != false) {
        output.writeBool(2, limit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, owner_);
      }
      if (limit_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, limit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit)) {
        return super.equals(obj);
      }
      dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit other = (dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit) obj;

      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getLimit());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47;/ MsgChangeP2PTransferLimit defines a  limit of transfer message
     *type MsgModifyP2PTransferLimit struct {
     *	Owner sdk.AccAddress `json:"owner"`
     *	Limit bool           `json:"limit"`
     *}
     * </pre>
     *
     * Protobuf type {@code dbchain.msgs.MsgModifyP2PTransferLimit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.MsgModifyP2PTransferLimit)
        dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit.class, dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit.Builder.class);
      }

      // Construct using dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        owner_ = "";

        limit_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit getDefaultInstanceForType() {
        return dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit build() {
        dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit buildPartial() {
        dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit result = new dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit(this);
        result.owner_ = owner_;
        result.limit_ = limit_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit) {
          return mergeFrom((dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit other) {
        if (other == dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit.getDefaultInstance()) return this;
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (other.getLimit() != false) {
          setLimit(other.getLimit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 1;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private boolean limit_ ;
      /**
       * <code>bool limit = 2;</code>
       * @return The limit.
       */
      @java.lang.Override
      public boolean getLimit() {
        return limit_;
      }
      /**
       * <code>bool limit = 2;</code>
       * @param value The limit to set.
       * @return This builder for chaining.
       */
      public Builder setLimit(boolean value) {
        
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool limit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimit() {
        
        limit_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.MsgModifyP2PTransferLimit)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.MsgModifyP2PTransferLimit)
    private static final dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit();
    }

    public static dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgModifyP2PTransferLimit>
        PARSER = new com.google.protobuf.AbstractParser<MsgModifyP2PTransferLimit>() {
      @java.lang.Override
      public MsgModifyP2PTransferLimit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgModifyP2PTransferLimit(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgModifyP2PTransferLimit> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgModifyP2PTransferLimit> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.MsgsLimitP2P.MsgModifyP2PTransferLimit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgModifyTokenKeeperMemberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.MsgModifyTokenKeeperMember)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>string action = 2;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>string member = 3;</code>
     * @return The member.
     */
    java.lang.String getMember();
    /**
     * <code>string member = 3;</code>
     * @return The bytes for member.
     */
    com.google.protobuf.ByteString
        getMemberBytes();
  }
  /**
   * <pre>
   *type MsgModifyTokenKeeperMember struct {
   *	Owner  sdk.AccAddress `json:"owner"`
   *	Action string         `json:"action"` //add or remove
   *	Member sdk.AccAddress `json:"member"`
   *}
   * </pre>
   *
   * Protobuf type {@code dbchain.msgs.MsgModifyTokenKeeperMember}
   */
  public static final class MsgModifyTokenKeeperMember extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.MsgModifyTokenKeeperMember)
      MsgModifyTokenKeeperMemberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgModifyTokenKeeperMember.newBuilder() to construct.
    private MsgModifyTokenKeeperMember(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgModifyTokenKeeperMember() {
      owner_ = "";
      action_ = "";
      member_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgModifyTokenKeeperMember();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgModifyTokenKeeperMember(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              member_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember.class, dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember.Builder.class);
    }

    public static final int OWNER_FIELD_NUMBER = 1;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object action_;
    /**
     * <code>string action = 2;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 2;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBER_FIELD_NUMBER = 3;
    private volatile java.lang.Object member_;
    /**
     * <code>string member = 3;</code>
     * @return The member.
     */
    @java.lang.Override
    public java.lang.String getMember() {
      java.lang.Object ref = member_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        member_ = s;
        return s;
      }
    }
    /**
     * <code>string member = 3;</code>
     * @return The bytes for member.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMemberBytes() {
      java.lang.Object ref = member_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        member_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, action_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(member_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, member_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, action_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(member_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, member_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember)) {
        return super.equals(obj);
      }
      dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember other = (dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember) obj;

      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (!getMember()
          .equals(other.getMember())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + MEMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMember().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *type MsgModifyTokenKeeperMember struct {
     *	Owner  sdk.AccAddress `json:"owner"`
     *	Action string         `json:"action"` //add or remove
     *	Member sdk.AccAddress `json:"member"`
     *}
     * </pre>
     *
     * Protobuf type {@code dbchain.msgs.MsgModifyTokenKeeperMember}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.MsgModifyTokenKeeperMember)
        dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMemberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember.class, dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember.Builder.class);
      }

      // Construct using dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        owner_ = "";

        action_ = "";

        member_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.MsgsLimitP2P.internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember getDefaultInstanceForType() {
        return dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember build() {
        dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember buildPartial() {
        dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember result = new dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember(this);
        result.owner_ = owner_;
        result.action_ = action_;
        result.member_ = member_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember) {
          return mergeFrom((dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember other) {
        if (other == dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember.getDefaultInstance()) return this;
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getMember().isEmpty()) {
          member_ = other.member_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 1;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 2;</code>
       * @return The action.
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 2;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 2;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 2;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object member_ = "";
      /**
       * <code>string member = 3;</code>
       * @return The member.
       */
      public java.lang.String getMember() {
        java.lang.Object ref = member_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          member_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string member = 3;</code>
       * @return The bytes for member.
       */
      public com.google.protobuf.ByteString
          getMemberBytes() {
        java.lang.Object ref = member_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          member_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string member = 3;</code>
       * @param value The member to set.
       * @return This builder for chaining.
       */
      public Builder setMember(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        member_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string member = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMember() {
        
        member_ = getDefaultInstance().getMember();
        onChanged();
        return this;
      }
      /**
       * <code>string member = 3;</code>
       * @param value The bytes for member to set.
       * @return This builder for chaining.
       */
      public Builder setMemberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        member_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.MsgModifyTokenKeeperMember)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.MsgModifyTokenKeeperMember)
    private static final dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember();
    }

    public static dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgModifyTokenKeeperMember>
        PARSER = new com.google.protobuf.AbstractParser<MsgModifyTokenKeeperMember>() {
      @java.lang.Override
      public MsgModifyTokenKeeperMember parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgModifyTokenKeeperMember(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgModifyTokenKeeperMember> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgModifyTokenKeeperMember> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.MsgsLimitP2P.MsgModifyTokenKeeperMember getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!dbchain/msgs/msgs_limit_p2p.proto\022\014dbc" +
      "hain.msgs\032\024gogoproto/gogo.proto\"9\n\031MsgMo" +
      "difyP2PTransferLimit\022\r\n\005owner\030\001 \001(\t\022\r\n\005l" +
      "imit\030\002 \001(\010\"K\n\032MsgModifyTokenKeeperMember" +
      "\022\r\n\005owner\030\001 \001(\t\022\016\n\006action\030\002 \001(\t\022\016\n\006membe" +
      "r\030\003 \001(\tB7Z5github.com/tharsis/ethermint/" +
      "x/dbchain/internal/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_MsgModifyP2PTransferLimit_descriptor,
        new java.lang.String[] { "Owner", "Limit", });
    internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_MsgModifyTokenKeeperMember_descriptor,
        new java.lang.String[] { "Owner", "Action", "Member", });
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
