// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbchain/msgs/msgs_friend.proto

package dbchain.msgs;

public final class MsgsFriend {
  private MsgsFriend() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgAddFriendOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.MsgAddFriend)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>string owner_name = 2;</code>
     * @return The ownerName.
     */
    java.lang.String getOwnerName();
    /**
     * <code>string owner_name = 2;</code>
     * @return The bytes for ownerName.
     */
    com.google.protobuf.ByteString
        getOwnerNameBytes();

    /**
     * <code>string friend_addr = 3;</code>
     * @return The friendAddr.
     */
    java.lang.String getFriendAddr();
    /**
     * <code>string friend_addr = 3;</code>
     * @return The bytes for friendAddr.
     */
    com.google.protobuf.ByteString
        getFriendAddrBytes();

    /**
     * <code>string friend_name = 4;</code>
     * @return The friendName.
     */
    java.lang.String getFriendName();
    /**
     * <code>string friend_name = 4;</code>
     * @return The bytes for friendName.
     */
    com.google.protobuf.ByteString
        getFriendNameBytes();
  }
  /**
   * <pre>
   *&#47;/ MsgAddFriend defines a CreateTable message
   *type MsgAddFriend struct {
   *	Owner      sdk.AccAddress `json:"owner"`
   *	OwnerName  string         `json:"owner_name"`
   *	FriendAddr string         `json:"friend_addr"`
   *	FriendName string         `json:"friend_name"`
   *}
   * </pre>
   *
   * Protobuf type {@code dbchain.msgs.MsgAddFriend}
   */
  public static final class MsgAddFriend extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.MsgAddFriend)
      MsgAddFriendOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgAddFriend.newBuilder() to construct.
    private MsgAddFriend(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgAddFriend() {
      owner_ = "";
      ownerName_ = "";
      friendAddr_ = "";
      friendName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgAddFriend();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgAddFriend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ownerName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              friendAddr_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              friendName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgAddFriend_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgAddFriend_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.MsgsFriend.MsgAddFriend.class, dbchain.msgs.MsgsFriend.MsgAddFriend.Builder.class);
    }

    public static final int OWNER_FIELD_NUMBER = 1;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNER_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object ownerName_;
    /**
     * <code>string owner_name = 2;</code>
     * @return The ownerName.
     */
    @java.lang.Override
    public java.lang.String getOwnerName() {
      java.lang.Object ref = ownerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerName_ = s;
        return s;
      }
    }
    /**
     * <code>string owner_name = 2;</code>
     * @return The bytes for ownerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerNameBytes() {
      java.lang.Object ref = ownerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIEND_ADDR_FIELD_NUMBER = 3;
    private volatile java.lang.Object friendAddr_;
    /**
     * <code>string friend_addr = 3;</code>
     * @return The friendAddr.
     */
    @java.lang.Override
    public java.lang.String getFriendAddr() {
      java.lang.Object ref = friendAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string friend_addr = 3;</code>
     * @return The bytes for friendAddr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFriendAddrBytes() {
      java.lang.Object ref = friendAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIEND_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object friendName_;
    /**
     * <code>string friend_name = 4;</code>
     * @return The friendName.
     */
    @java.lang.Override
    public java.lang.String getFriendName() {
      java.lang.Object ref = friendName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendName_ = s;
        return s;
      }
    }
    /**
     * <code>string friend_name = 4;</code>
     * @return The bytes for friendName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFriendNameBytes() {
      java.lang.Object ref = friendName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ownerName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ownerName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(friendAddr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, friendAddr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(friendName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, friendName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ownerName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ownerName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(friendAddr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, friendAddr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(friendName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, friendName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.MsgsFriend.MsgAddFriend)) {
        return super.equals(obj);
      }
      dbchain.msgs.MsgsFriend.MsgAddFriend other = (dbchain.msgs.MsgsFriend.MsgAddFriend) obj;

      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!getOwnerName()
          .equals(other.getOwnerName())) return false;
      if (!getFriendAddr()
          .equals(other.getFriendAddr())) return false;
      if (!getFriendName()
          .equals(other.getFriendName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + OWNER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getOwnerName().hashCode();
      hash = (37 * hash) + FRIEND_ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getFriendAddr().hashCode();
      hash = (37 * hash) + FRIEND_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFriendName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgAddFriend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.MsgsFriend.MsgAddFriend prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47;/ MsgAddFriend defines a CreateTable message
     *type MsgAddFriend struct {
     *	Owner      sdk.AccAddress `json:"owner"`
     *	OwnerName  string         `json:"owner_name"`
     *	FriendAddr string         `json:"friend_addr"`
     *	FriendName string         `json:"friend_name"`
     *}
     * </pre>
     *
     * Protobuf type {@code dbchain.msgs.MsgAddFriend}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.MsgAddFriend)
        dbchain.msgs.MsgsFriend.MsgAddFriendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgAddFriend_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgAddFriend_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.MsgsFriend.MsgAddFriend.class, dbchain.msgs.MsgsFriend.MsgAddFriend.Builder.class);
      }

      // Construct using dbchain.msgs.MsgsFriend.MsgAddFriend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        owner_ = "";

        ownerName_ = "";

        friendAddr_ = "";

        friendName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgAddFriend_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgAddFriend getDefaultInstanceForType() {
        return dbchain.msgs.MsgsFriend.MsgAddFriend.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgAddFriend build() {
        dbchain.msgs.MsgsFriend.MsgAddFriend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgAddFriend buildPartial() {
        dbchain.msgs.MsgsFriend.MsgAddFriend result = new dbchain.msgs.MsgsFriend.MsgAddFriend(this);
        result.owner_ = owner_;
        result.ownerName_ = ownerName_;
        result.friendAddr_ = friendAddr_;
        result.friendName_ = friendName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.MsgsFriend.MsgAddFriend) {
          return mergeFrom((dbchain.msgs.MsgsFriend.MsgAddFriend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.MsgsFriend.MsgAddFriend other) {
        if (other == dbchain.msgs.MsgsFriend.MsgAddFriend.getDefaultInstance()) return this;
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (!other.getOwnerName().isEmpty()) {
          ownerName_ = other.ownerName_;
          onChanged();
        }
        if (!other.getFriendAddr().isEmpty()) {
          friendAddr_ = other.friendAddr_;
          onChanged();
        }
        if (!other.getFriendName().isEmpty()) {
          friendName_ = other.friendName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.MsgsFriend.MsgAddFriend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.MsgsFriend.MsgAddFriend) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 1;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ownerName_ = "";
      /**
       * <code>string owner_name = 2;</code>
       * @return The ownerName.
       */
      public java.lang.String getOwnerName() {
        java.lang.Object ref = ownerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ownerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner_name = 2;</code>
       * @return The bytes for ownerName.
       */
      public com.google.protobuf.ByteString
          getOwnerNameBytes() {
        java.lang.Object ref = ownerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ownerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner_name = 2;</code>
       * @param value The ownerName to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnerName() {
        
        ownerName_ = getDefaultInstance().getOwnerName();
        onChanged();
        return this;
      }
      /**
       * <code>string owner_name = 2;</code>
       * @param value The bytes for ownerName to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ownerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object friendAddr_ = "";
      /**
       * <code>string friend_addr = 3;</code>
       * @return The friendAddr.
       */
      public java.lang.String getFriendAddr() {
        java.lang.Object ref = friendAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          friendAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string friend_addr = 3;</code>
       * @return The bytes for friendAddr.
       */
      public com.google.protobuf.ByteString
          getFriendAddrBytes() {
        java.lang.Object ref = friendAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string friend_addr = 3;</code>
       * @param value The friendAddr to set.
       * @return This builder for chaining.
       */
      public Builder setFriendAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        friendAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string friend_addr = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFriendAddr() {
        
        friendAddr_ = getDefaultInstance().getFriendAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string friend_addr = 3;</code>
       * @param value The bytes for friendAddr to set.
       * @return This builder for chaining.
       */
      public Builder setFriendAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        friendAddr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object friendName_ = "";
      /**
       * <code>string friend_name = 4;</code>
       * @return The friendName.
       */
      public java.lang.String getFriendName() {
        java.lang.Object ref = friendName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          friendName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string friend_name = 4;</code>
       * @return The bytes for friendName.
       */
      public com.google.protobuf.ByteString
          getFriendNameBytes() {
        java.lang.Object ref = friendName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string friend_name = 4;</code>
       * @param value The friendName to set.
       * @return This builder for chaining.
       */
      public Builder setFriendName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        friendName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string friend_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFriendName() {
        
        friendName_ = getDefaultInstance().getFriendName();
        onChanged();
        return this;
      }
      /**
       * <code>string friend_name = 4;</code>
       * @param value The bytes for friendName to set.
       * @return This builder for chaining.
       */
      public Builder setFriendNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        friendName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.MsgAddFriend)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.MsgAddFriend)
    private static final dbchain.msgs.MsgsFriend.MsgAddFriend DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.MsgsFriend.MsgAddFriend();
    }

    public static dbchain.msgs.MsgsFriend.MsgAddFriend getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgAddFriend>
        PARSER = new com.google.protobuf.AbstractParser<MsgAddFriend>() {
      @java.lang.Override
      public MsgAddFriend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgAddFriend(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgAddFriend> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgAddFriend> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.MsgsFriend.MsgAddFriend getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgDropFriendOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.MsgDropFriend)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>string friend_addr = 2;</code>
     * @return The friendAddr.
     */
    java.lang.String getFriendAddr();
    /**
     * <code>string friend_addr = 2;</code>
     * @return The bytes for friendAddr.
     */
    com.google.protobuf.ByteString
        getFriendAddrBytes();
  }
  /**
   * <pre>
   *type MsgDropFriend struct {
   *	Owner      sdk.AccAddress `json:"owner"`
   *	FriendAddr string         `json:"friend_addr"`
   *}
   * </pre>
   *
   * Protobuf type {@code dbchain.msgs.MsgDropFriend}
   */
  public static final class MsgDropFriend extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.MsgDropFriend)
      MsgDropFriendOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgDropFriend.newBuilder() to construct.
    private MsgDropFriend(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgDropFriend() {
      owner_ = "";
      friendAddr_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgDropFriend();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgDropFriend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              friendAddr_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgDropFriend_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgDropFriend_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.MsgsFriend.MsgDropFriend.class, dbchain.msgs.MsgsFriend.MsgDropFriend.Builder.class);
    }

    public static final int OWNER_FIELD_NUMBER = 1;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIEND_ADDR_FIELD_NUMBER = 2;
    private volatile java.lang.Object friendAddr_;
    /**
     * <code>string friend_addr = 2;</code>
     * @return The friendAddr.
     */
    @java.lang.Override
    public java.lang.String getFriendAddr() {
      java.lang.Object ref = friendAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string friend_addr = 2;</code>
     * @return The bytes for friendAddr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFriendAddrBytes() {
      java.lang.Object ref = friendAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(friendAddr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, friendAddr_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(friendAddr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, friendAddr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.MsgsFriend.MsgDropFriend)) {
        return super.equals(obj);
      }
      dbchain.msgs.MsgsFriend.MsgDropFriend other = (dbchain.msgs.MsgsFriend.MsgDropFriend) obj;

      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!getFriendAddr()
          .equals(other.getFriendAddr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + FRIEND_ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getFriendAddr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgDropFriend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.MsgsFriend.MsgDropFriend prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *type MsgDropFriend struct {
     *	Owner      sdk.AccAddress `json:"owner"`
     *	FriendAddr string         `json:"friend_addr"`
     *}
     * </pre>
     *
     * Protobuf type {@code dbchain.msgs.MsgDropFriend}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.MsgDropFriend)
        dbchain.msgs.MsgsFriend.MsgDropFriendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgDropFriend_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgDropFriend_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.MsgsFriend.MsgDropFriend.class, dbchain.msgs.MsgsFriend.MsgDropFriend.Builder.class);
      }

      // Construct using dbchain.msgs.MsgsFriend.MsgDropFriend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        owner_ = "";

        friendAddr_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgDropFriend_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgDropFriend getDefaultInstanceForType() {
        return dbchain.msgs.MsgsFriend.MsgDropFriend.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgDropFriend build() {
        dbchain.msgs.MsgsFriend.MsgDropFriend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgDropFriend buildPartial() {
        dbchain.msgs.MsgsFriend.MsgDropFriend result = new dbchain.msgs.MsgsFriend.MsgDropFriend(this);
        result.owner_ = owner_;
        result.friendAddr_ = friendAddr_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.MsgsFriend.MsgDropFriend) {
          return mergeFrom((dbchain.msgs.MsgsFriend.MsgDropFriend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.MsgsFriend.MsgDropFriend other) {
        if (other == dbchain.msgs.MsgsFriend.MsgDropFriend.getDefaultInstance()) return this;
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (!other.getFriendAddr().isEmpty()) {
          friendAddr_ = other.friendAddr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.MsgsFriend.MsgDropFriend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.MsgsFriend.MsgDropFriend) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 1;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object friendAddr_ = "";
      /**
       * <code>string friend_addr = 2;</code>
       * @return The friendAddr.
       */
      public java.lang.String getFriendAddr() {
        java.lang.Object ref = friendAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          friendAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string friend_addr = 2;</code>
       * @return The bytes for friendAddr.
       */
      public com.google.protobuf.ByteString
          getFriendAddrBytes() {
        java.lang.Object ref = friendAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string friend_addr = 2;</code>
       * @param value The friendAddr to set.
       * @return This builder for chaining.
       */
      public Builder setFriendAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        friendAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string friend_addr = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFriendAddr() {
        
        friendAddr_ = getDefaultInstance().getFriendAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string friend_addr = 2;</code>
       * @param value The bytes for friendAddr to set.
       * @return This builder for chaining.
       */
      public Builder setFriendAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        friendAddr_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.MsgDropFriend)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.MsgDropFriend)
    private static final dbchain.msgs.MsgsFriend.MsgDropFriend DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.MsgsFriend.MsgDropFriend();
    }

    public static dbchain.msgs.MsgsFriend.MsgDropFriend getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgDropFriend>
        PARSER = new com.google.protobuf.AbstractParser<MsgDropFriend>() {
      @java.lang.Override
      public MsgDropFriend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgDropFriend(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgDropFriend> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgDropFriend> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.MsgsFriend.MsgDropFriend getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgRespondFriendOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.MsgRespondFriend)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>string friend_addr = 2;</code>
     * @return The friendAddr.
     */
    java.lang.String getFriendAddr();
    /**
     * <code>string friend_addr = 2;</code>
     * @return The bytes for friendAddr.
     */
    com.google.protobuf.ByteString
        getFriendAddrBytes();

    /**
     * <code>string action = 3;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <code>string action = 3;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();
  }
  /**
   * <pre>
   *&#47;/ MsgRespondFriend defines a CreateTable message
   *type MsgRespondFriend struct {
   *	Owner      sdk.AccAddress `json:"owner"`
   *	FriendAddr string         `json:"friend_addr"`
   *	Action     string         `json:"action"`
   *}
   * </pre>
   *
   * Protobuf type {@code dbchain.msgs.MsgRespondFriend}
   */
  public static final class MsgRespondFriend extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.MsgRespondFriend)
      MsgRespondFriendOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgRespondFriend.newBuilder() to construct.
    private MsgRespondFriend(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgRespondFriend() {
      owner_ = "";
      friendAddr_ = "";
      action_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgRespondFriend();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgRespondFriend(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              friendAddr_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgRespondFriend_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgRespondFriend_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.MsgsFriend.MsgRespondFriend.class, dbchain.msgs.MsgsFriend.MsgRespondFriend.Builder.class);
    }

    public static final int OWNER_FIELD_NUMBER = 1;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRIEND_ADDR_FIELD_NUMBER = 2;
    private volatile java.lang.Object friendAddr_;
    /**
     * <code>string friend_addr = 2;</code>
     * @return The friendAddr.
     */
    @java.lang.Override
    public java.lang.String getFriendAddr() {
      java.lang.Object ref = friendAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        friendAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string friend_addr = 2;</code>
     * @return The bytes for friendAddr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFriendAddrBytes() {
      java.lang.Object ref = friendAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object action_;
    /**
     * <code>string action = 3;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 3;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(friendAddr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, friendAddr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, action_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(friendAddr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, friendAddr_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, action_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.MsgsFriend.MsgRespondFriend)) {
        return super.equals(obj);
      }
      dbchain.msgs.MsgsFriend.MsgRespondFriend other = (dbchain.msgs.MsgsFriend.MsgRespondFriend) obj;

      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!getFriendAddr()
          .equals(other.getFriendAddr())) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + FRIEND_ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getFriendAddr().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsFriend.MsgRespondFriend parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.MsgsFriend.MsgRespondFriend prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47;/ MsgRespondFriend defines a CreateTable message
     *type MsgRespondFriend struct {
     *	Owner      sdk.AccAddress `json:"owner"`
     *	FriendAddr string         `json:"friend_addr"`
     *	Action     string         `json:"action"`
     *}
     * </pre>
     *
     * Protobuf type {@code dbchain.msgs.MsgRespondFriend}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.MsgRespondFriend)
        dbchain.msgs.MsgsFriend.MsgRespondFriendOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgRespondFriend_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgRespondFriend_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.MsgsFriend.MsgRespondFriend.class, dbchain.msgs.MsgsFriend.MsgRespondFriend.Builder.class);
      }

      // Construct using dbchain.msgs.MsgsFriend.MsgRespondFriend.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        owner_ = "";

        friendAddr_ = "";

        action_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.MsgsFriend.internal_static_dbchain_msgs_MsgRespondFriend_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgRespondFriend getDefaultInstanceForType() {
        return dbchain.msgs.MsgsFriend.MsgRespondFriend.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgRespondFriend build() {
        dbchain.msgs.MsgsFriend.MsgRespondFriend result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsFriend.MsgRespondFriend buildPartial() {
        dbchain.msgs.MsgsFriend.MsgRespondFriend result = new dbchain.msgs.MsgsFriend.MsgRespondFriend(this);
        result.owner_ = owner_;
        result.friendAddr_ = friendAddr_;
        result.action_ = action_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.MsgsFriend.MsgRespondFriend) {
          return mergeFrom((dbchain.msgs.MsgsFriend.MsgRespondFriend)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.MsgsFriend.MsgRespondFriend other) {
        if (other == dbchain.msgs.MsgsFriend.MsgRespondFriend.getDefaultInstance()) return this;
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (!other.getFriendAddr().isEmpty()) {
          friendAddr_ = other.friendAddr_;
          onChanged();
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.MsgsFriend.MsgRespondFriend parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.MsgsFriend.MsgRespondFriend) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 1;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object friendAddr_ = "";
      /**
       * <code>string friend_addr = 2;</code>
       * @return The friendAddr.
       */
      public java.lang.String getFriendAddr() {
        java.lang.Object ref = friendAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          friendAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string friend_addr = 2;</code>
       * @return The bytes for friendAddr.
       */
      public com.google.protobuf.ByteString
          getFriendAddrBytes() {
        java.lang.Object ref = friendAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string friend_addr = 2;</code>
       * @param value The friendAddr to set.
       * @return This builder for chaining.
       */
      public Builder setFriendAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        friendAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string friend_addr = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFriendAddr() {
        
        friendAddr_ = getDefaultInstance().getFriendAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string friend_addr = 2;</code>
       * @param value The bytes for friendAddr to set.
       * @return This builder for chaining.
       */
      public Builder setFriendAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        friendAddr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 3;</code>
       * @return The action.
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 3;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 3;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 3;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.MsgRespondFriend)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.MsgRespondFriend)
    private static final dbchain.msgs.MsgsFriend.MsgRespondFriend DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.MsgsFriend.MsgRespondFriend();
    }

    public static dbchain.msgs.MsgsFriend.MsgRespondFriend getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgRespondFriend>
        PARSER = new com.google.protobuf.AbstractParser<MsgRespondFriend>() {
      @java.lang.Override
      public MsgRespondFriend parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgRespondFriend(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgRespondFriend> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgRespondFriend> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.MsgsFriend.MsgRespondFriend getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_MsgAddFriend_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_MsgAddFriend_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_MsgDropFriend_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_MsgDropFriend_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_MsgRespondFriend_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_MsgRespondFriend_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036dbchain/msgs/msgs_friend.proto\022\014dbchai" +
      "n.msgs\032\024gogoproto/gogo.proto\"[\n\014MsgAddFr" +
      "iend\022\r\n\005owner\030\001 \001(\t\022\022\n\nowner_name\030\002 \001(\t\022" +
      "\023\n\013friend_addr\030\003 \001(\t\022\023\n\013friend_name\030\004 \001(" +
      "\t\"3\n\rMsgDropFriend\022\r\n\005owner\030\001 \001(\t\022\023\n\013fri" +
      "end_addr\030\002 \001(\t\"F\n\020MsgRespondFriend\022\r\n\005ow" +
      "ner\030\001 \001(\t\022\023\n\013friend_addr\030\002 \001(\t\022\016\n\006action" +
      "\030\003 \001(\tB7Z5github.com/tharsis/ethermint/x" +
      "/dbchain/internal/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_dbchain_msgs_MsgAddFriend_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dbchain_msgs_MsgAddFriend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_MsgAddFriend_descriptor,
        new java.lang.String[] { "Owner", "OwnerName", "FriendAddr", "FriendName", });
    internal_static_dbchain_msgs_MsgDropFriend_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dbchain_msgs_MsgDropFriend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_MsgDropFriend_descriptor,
        new java.lang.String[] { "Owner", "FriendAddr", });
    internal_static_dbchain_msgs_MsgRespondFriend_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dbchain_msgs_MsgRespondFriend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_MsgRespondFriend_descriptor,
        new java.lang.String[] { "Owner", "FriendAddr", "Action", });
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
