// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbchain/msgs/msgs_custom_querier.proto

package dbchain.msgs;

public final class MsgsCustomQuerier {
  private MsgsCustomQuerier() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgAddCustomQuerierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.MsgAddCustomQuerier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>string app_code = 2;</code>
     * @return The appCode.
     */
    java.lang.String getAppCode();
    /**
     * <code>string app_code = 2;</code>
     * @return The bytes for appCode.
     */
    com.google.protobuf.ByteString
        getAppCodeBytes();

    /**
     * <code>string querier_name = 3;</code>
     * @return The querierName.
     */
    java.lang.String getQuerierName();
    /**
     * <code>string querier_name = 3;</code>
     * @return The bytes for querierName.
     */
    com.google.protobuf.ByteString
        getQuerierNameBytes();

    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string body = 5;</code>
     * @return The body.
     */
    java.lang.String getBody();
    /**
     * <code>string body = 5;</code>
     * @return The bytes for body.
     */
    com.google.protobuf.ByteString
        getBodyBytes();
  }
  /**
   * Protobuf type {@code dbchain.msgs.MsgAddCustomQuerier}
   */
  public static final class MsgAddCustomQuerier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.MsgAddCustomQuerier)
      MsgAddCustomQuerierOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgAddCustomQuerier.newBuilder() to construct.
    private MsgAddCustomQuerier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgAddCustomQuerier() {
      owner_ = "";
      appCode_ = "";
      querierName_ = "";
      description_ = "";
      body_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgAddCustomQuerier();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgAddCustomQuerier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              querierName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              body_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgAddCustomQuerier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgAddCustomQuerier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier.class, dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier.Builder.class);
    }

    public static final int OWNER_FIELD_NUMBER = 1;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object appCode_;
    /**
     * <code>string app_code = 2;</code>
     * @return The appCode.
     */
    @java.lang.Override
    public java.lang.String getAppCode() {
      java.lang.Object ref = appCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appCode_ = s;
        return s;
      }
    }
    /**
     * <code>string app_code = 2;</code>
     * @return The bytes for appCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppCodeBytes() {
      java.lang.Object ref = appCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUERIER_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object querierName_;
    /**
     * <code>string querier_name = 3;</code>
     * @return The querierName.
     */
    @java.lang.Override
    public java.lang.String getQuerierName() {
      java.lang.Object ref = querierName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        querierName_ = s;
        return s;
      }
    }
    /**
     * <code>string querier_name = 3;</code>
     * @return The bytes for querierName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQuerierNameBytes() {
      java.lang.Object ref = querierName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        querierName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private volatile java.lang.Object body_;
    /**
     * <code>string body = 5;</code>
     * @return The body.
     */
    @java.lang.Override
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      }
    }
    /**
     * <code>string body = 5;</code>
     * @return The bytes for body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(querierName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, querierName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(querierName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, querierName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(body_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier)) {
        return super.equals(obj);
      }
      dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier other = (dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier) obj;

      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!getAppCode()
          .equals(other.getAppCode())) return false;
      if (!getQuerierName()
          .equals(other.getQuerierName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + APP_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAppCode().hashCode();
      hash = (37 * hash) + QUERIER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getQuerierName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dbchain.msgs.MsgAddCustomQuerier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.MsgAddCustomQuerier)
        dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgAddCustomQuerier_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgAddCustomQuerier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier.class, dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier.Builder.class);
      }

      // Construct using dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        owner_ = "";

        appCode_ = "";

        querierName_ = "";

        description_ = "";

        body_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgAddCustomQuerier_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier getDefaultInstanceForType() {
        return dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier build() {
        dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier buildPartial() {
        dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier result = new dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier(this);
        result.owner_ = owner_;
        result.appCode_ = appCode_;
        result.querierName_ = querierName_;
        result.description_ = description_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier) {
          return mergeFrom((dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier other) {
        if (other == dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier.getDefaultInstance()) return this;
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (!other.getAppCode().isEmpty()) {
          appCode_ = other.appCode_;
          onChanged();
        }
        if (!other.getQuerierName().isEmpty()) {
          querierName_ = other.querierName_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getBody().isEmpty()) {
          body_ = other.body_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 1;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appCode_ = "";
      /**
       * <code>string app_code = 2;</code>
       * @return The appCode.
       */
      public java.lang.String getAppCode() {
        java.lang.Object ref = appCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_code = 2;</code>
       * @return The bytes for appCode.
       */
      public com.google.protobuf.ByteString
          getAppCodeBytes() {
        java.lang.Object ref = appCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_code = 2;</code>
       * @param value The appCode to set.
       * @return This builder for chaining.
       */
      public Builder setAppCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppCode() {
        
        appCode_ = getDefaultInstance().getAppCode();
        onChanged();
        return this;
      }
      /**
       * <code>string app_code = 2;</code>
       * @param value The bytes for appCode to set.
       * @return This builder for chaining.
       */
      public Builder setAppCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object querierName_ = "";
      /**
       * <code>string querier_name = 3;</code>
       * @return The querierName.
       */
      public java.lang.String getQuerierName() {
        java.lang.Object ref = querierName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          querierName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string querier_name = 3;</code>
       * @return The bytes for querierName.
       */
      public com.google.protobuf.ByteString
          getQuerierNameBytes() {
        java.lang.Object ref = querierName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          querierName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string querier_name = 3;</code>
       * @param value The querierName to set.
       * @return This builder for chaining.
       */
      public Builder setQuerierName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        querierName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string querier_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuerierName() {
        
        querierName_ = getDefaultInstance().getQuerierName();
        onChanged();
        return this;
      }
      /**
       * <code>string querier_name = 3;</code>
       * @param value The bytes for querierName to set.
       * @return This builder for chaining.
       */
      public Builder setQuerierNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        querierName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 4;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 4;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 4;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 4;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>string body = 5;</code>
       * @return The body.
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string body = 5;</code>
       * @return The bytes for body.
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string body = 5;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string body = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>string body = 5;</code>
       * @param value The bytes for body to set.
       * @return This builder for chaining.
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        body_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.MsgAddCustomQuerier)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.MsgAddCustomQuerier)
    private static final dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier();
    }

    public static dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgAddCustomQuerier>
        PARSER = new com.google.protobuf.AbstractParser<MsgAddCustomQuerier>() {
      @java.lang.Override
      public MsgAddCustomQuerier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgAddCustomQuerier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgAddCustomQuerier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgAddCustomQuerier> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.MsgsCustomQuerier.MsgAddCustomQuerier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgDropCustomQuerierOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.MsgDropCustomQuerier)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>string app_code = 2;</code>
     * @return The appCode.
     */
    java.lang.String getAppCode();
    /**
     * <code>string app_code = 2;</code>
     * @return The bytes for appCode.
     */
    com.google.protobuf.ByteString
        getAppCodeBytes();

    /**
     * <code>string querier_name = 3;</code>
     * @return The querierName.
     */
    java.lang.String getQuerierName();
    /**
     * <code>string querier_name = 3;</code>
     * @return The bytes for querierName.
     */
    com.google.protobuf.ByteString
        getQuerierNameBytes();
  }
  /**
   * <pre>
   *type MsgDropCustomQuerier struct {
   *	Owner       sdk.AccAddress `json:"owner"`
   *	AppCode     string         `json:"app_code"`
   *	QuerierName string         `json:"querier_name"`
   *}
   * </pre>
   *
   * Protobuf type {@code dbchain.msgs.MsgDropCustomQuerier}
   */
  public static final class MsgDropCustomQuerier extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.MsgDropCustomQuerier)
      MsgDropCustomQuerierOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgDropCustomQuerier.newBuilder() to construct.
    private MsgDropCustomQuerier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgDropCustomQuerier() {
      owner_ = "";
      appCode_ = "";
      querierName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgDropCustomQuerier();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgDropCustomQuerier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              appCode_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              querierName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgDropCustomQuerier_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgDropCustomQuerier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier.class, dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier.Builder.class);
    }

    public static final int OWNER_FIELD_NUMBER = 1;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 1;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 1;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object appCode_;
    /**
     * <code>string app_code = 2;</code>
     * @return The appCode.
     */
    @java.lang.Override
    public java.lang.String getAppCode() {
      java.lang.Object ref = appCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appCode_ = s;
        return s;
      }
    }
    /**
     * <code>string app_code = 2;</code>
     * @return The bytes for appCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppCodeBytes() {
      java.lang.Object ref = appCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUERIER_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object querierName_;
    /**
     * <code>string querier_name = 3;</code>
     * @return The querierName.
     */
    @java.lang.Override
    public java.lang.String getQuerierName() {
      java.lang.Object ref = querierName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        querierName_ = s;
        return s;
      }
    }
    /**
     * <code>string querier_name = 3;</code>
     * @return The bytes for querierName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQuerierNameBytes() {
      java.lang.Object ref = querierName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        querierName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, appCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(querierName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, querierName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, owner_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, appCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(querierName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, querierName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier)) {
        return super.equals(obj);
      }
      dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier other = (dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier) obj;

      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!getAppCode()
          .equals(other.getAppCode())) return false;
      if (!getQuerierName()
          .equals(other.getQuerierName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + APP_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAppCode().hashCode();
      hash = (37 * hash) + QUERIER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getQuerierName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *type MsgDropCustomQuerier struct {
     *	Owner       sdk.AccAddress `json:"owner"`
     *	AppCode     string         `json:"app_code"`
     *	QuerierName string         `json:"querier_name"`
     *}
     * </pre>
     *
     * Protobuf type {@code dbchain.msgs.MsgDropCustomQuerier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.MsgDropCustomQuerier)
        dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgDropCustomQuerier_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgDropCustomQuerier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier.class, dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier.Builder.class);
      }

      // Construct using dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        owner_ = "";

        appCode_ = "";

        querierName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.MsgsCustomQuerier.internal_static_dbchain_msgs_MsgDropCustomQuerier_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier getDefaultInstanceForType() {
        return dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier build() {
        dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier buildPartial() {
        dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier result = new dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier(this);
        result.owner_ = owner_;
        result.appCode_ = appCode_;
        result.querierName_ = querierName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier) {
          return mergeFrom((dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier other) {
        if (other == dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier.getDefaultInstance()) return this;
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (!other.getAppCode().isEmpty()) {
          appCode_ = other.appCode_;
          onChanged();
        }
        if (!other.getQuerierName().isEmpty()) {
          querierName_ = other.querierName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 1;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 1;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appCode_ = "";
      /**
       * <code>string app_code = 2;</code>
       * @return The appCode.
       */
      public java.lang.String getAppCode() {
        java.lang.Object ref = appCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_code = 2;</code>
       * @return The bytes for appCode.
       */
      public com.google.protobuf.ByteString
          getAppCodeBytes() {
        java.lang.Object ref = appCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_code = 2;</code>
       * @param value The appCode to set.
       * @return This builder for chaining.
       */
      public Builder setAppCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppCode() {
        
        appCode_ = getDefaultInstance().getAppCode();
        onChanged();
        return this;
      }
      /**
       * <code>string app_code = 2;</code>
       * @param value The bytes for appCode to set.
       * @return This builder for chaining.
       */
      public Builder setAppCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object querierName_ = "";
      /**
       * <code>string querier_name = 3;</code>
       * @return The querierName.
       */
      public java.lang.String getQuerierName() {
        java.lang.Object ref = querierName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          querierName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string querier_name = 3;</code>
       * @return The bytes for querierName.
       */
      public com.google.protobuf.ByteString
          getQuerierNameBytes() {
        java.lang.Object ref = querierName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          querierName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string querier_name = 3;</code>
       * @param value The querierName to set.
       * @return This builder for chaining.
       */
      public Builder setQuerierName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        querierName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string querier_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuerierName() {
        
        querierName_ = getDefaultInstance().getQuerierName();
        onChanged();
        return this;
      }
      /**
       * <code>string querier_name = 3;</code>
       * @param value The bytes for querierName to set.
       * @return This builder for chaining.
       */
      public Builder setQuerierNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        querierName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.MsgDropCustomQuerier)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.MsgDropCustomQuerier)
    private static final dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier();
    }

    public static dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgDropCustomQuerier>
        PARSER = new com.google.protobuf.AbstractParser<MsgDropCustomQuerier>() {
      @java.lang.Override
      public MsgDropCustomQuerier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgDropCustomQuerier(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgDropCustomQuerier> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgDropCustomQuerier> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.MsgsCustomQuerier.MsgDropCustomQuerier getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_MsgAddCustomQuerier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_MsgAddCustomQuerier_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_MsgDropCustomQuerier_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_MsgDropCustomQuerier_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&dbchain/msgs/msgs_custom_querier.proto" +
      "\022\014dbchain.msgs\032\024gogoproto/gogo.proto\"o\n\023" +
      "MsgAddCustomQuerier\022\r\n\005owner\030\001 \001(\t\022\020\n\010ap" +
      "p_code\030\002 \001(\t\022\024\n\014querier_name\030\003 \001(\t\022\023\n\013de" +
      "scription\030\004 \001(\t\022\014\n\004body\030\005 \001(\t\"M\n\024MsgDrop" +
      "CustomQuerier\022\r\n\005owner\030\001 \001(\t\022\020\n\010app_code" +
      "\030\002 \001(\t\022\024\n\014querier_name\030\003 \001(\tB7Z5github.c" +
      "om/tharsis/ethermint/x/dbchain/internal/" +
      "typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_dbchain_msgs_MsgAddCustomQuerier_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dbchain_msgs_MsgAddCustomQuerier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_MsgAddCustomQuerier_descriptor,
        new java.lang.String[] { "Owner", "AppCode", "QuerierName", "Description", "Body", });
    internal_static_dbchain_msgs_MsgDropCustomQuerier_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dbchain_msgs_MsgDropCustomQuerier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_MsgDropCustomQuerier_descriptor,
        new java.lang.String[] { "Owner", "AppCode", "QuerierName", });
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
