// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbchain/msgs/msgs_group_member.proto

package dbchain.msgs;

public final class MsgsGroupMember {
  private MsgsGroupMember() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgModifyGroupMemberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.MsgModifyGroupMember)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string app_code = 1;</code>
     * @return The appCode.
     */
    java.lang.String getAppCode();
    /**
     * <code>string app_code = 1;</code>
     * @return The bytes for appCode.
     */
    com.google.protobuf.ByteString
        getAppCodeBytes();

    /**
     * <code>string group = 2;</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 2;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>string action = 3;</code>
     * @return The action.
     */
    java.lang.String getAction();
    /**
     * <code>string action = 3;</code>
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
        getActionBytes();

    /**
     * <code>string member = 4;</code>
     * @return The member.
     */
    java.lang.String getMember();
    /**
     * <code>string member = 4;</code>
     * @return The bytes for member.
     */
    com.google.protobuf.ByteString
        getMemberBytes();

    /**
     * <code>string owner = 5;</code>
     * @return The owner.
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 5;</code>
     * @return The bytes for owner.
     */
    com.google.protobuf.ByteString
        getOwnerBytes();
  }
  /**
   * <pre>
   *type MsgModifyGroupMember struct {
   *	AppCode string         `json:"app_code"`
   *	Group   string         `json:"group"`
   *	Action  string         `json:"action"`
   *	Member  sdk.AccAddress `json:"member"`
   *	Owner   sdk.AccAddress `json:"owner"`
   *}
   * </pre>
   *
   * Protobuf type {@code dbchain.msgs.MsgModifyGroupMember}
   */
  public static final class MsgModifyGroupMember extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.MsgModifyGroupMember)
      MsgModifyGroupMemberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgModifyGroupMember.newBuilder() to construct.
    private MsgModifyGroupMember(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgModifyGroupMember() {
      appCode_ = "";
      group_ = "";
      action_ = "";
      member_ = "";
      owner_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgModifyGroupMember();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgModifyGroupMember(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              member_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.MsgsGroupMember.internal_static_dbchain_msgs_MsgModifyGroupMember_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.MsgsGroupMember.internal_static_dbchain_msgs_MsgModifyGroupMember_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember.class, dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember.Builder.class);
    }

    public static final int APP_CODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object appCode_;
    /**
     * <code>string app_code = 1;</code>
     * @return The appCode.
     */
    @java.lang.Override
    public java.lang.String getAppCode() {
      java.lang.Object ref = appCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appCode_ = s;
        return s;
      }
    }
    /**
     * <code>string app_code = 1;</code>
     * @return The bytes for appCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppCodeBytes() {
      java.lang.Object ref = appCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 2;
    private volatile java.lang.Object group_;
    /**
     * <code>string group = 2;</code>
     * @return The group.
     */
    @java.lang.Override
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 2;</code>
     * @return The bytes for group.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object action_;
    /**
     * <code>string action = 3;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 3;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMBER_FIELD_NUMBER = 4;
    private volatile java.lang.Object member_;
    /**
     * <code>string member = 4;</code>
     * @return The member.
     */
    @java.lang.Override
    public java.lang.String getMember() {
      java.lang.Object ref = member_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        member_ = s;
        return s;
      }
    }
    /**
     * <code>string member = 4;</code>
     * @return The bytes for member.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMemberBytes() {
      java.lang.Object ref = member_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        member_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNER_FIELD_NUMBER = 5;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 5;</code>
     * @return The owner.
     */
    @java.lang.Override
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 5;</code>
     * @return The bytes for owner.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(group_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, group_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, action_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(member_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, member_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, owner_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(appCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(group_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, group_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(action_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, action_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(member_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, member_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(owner_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, owner_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember)) {
        return super.equals(obj);
      }
      dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember other = (dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember) obj;

      if (!getAppCode()
          .equals(other.getAppCode())) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getAction()
          .equals(other.getAction())) return false;
      if (!getMember()
          .equals(other.getMember())) return false;
      if (!getOwner()
          .equals(other.getOwner())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APP_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getAppCode().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (37 * hash) + MEMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMember().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *type MsgModifyGroupMember struct {
     *	AppCode string         `json:"app_code"`
     *	Group   string         `json:"group"`
     *	Action  string         `json:"action"`
     *	Member  sdk.AccAddress `json:"member"`
     *	Owner   sdk.AccAddress `json:"owner"`
     *}
     * </pre>
     *
     * Protobuf type {@code dbchain.msgs.MsgModifyGroupMember}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.MsgModifyGroupMember)
        dbchain.msgs.MsgsGroupMember.MsgModifyGroupMemberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.MsgsGroupMember.internal_static_dbchain_msgs_MsgModifyGroupMember_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.MsgsGroupMember.internal_static_dbchain_msgs_MsgModifyGroupMember_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember.class, dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember.Builder.class);
      }

      // Construct using dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appCode_ = "";

        group_ = "";

        action_ = "";

        member_ = "";

        owner_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.MsgsGroupMember.internal_static_dbchain_msgs_MsgModifyGroupMember_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember getDefaultInstanceForType() {
        return dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember build() {
        dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember buildPartial() {
        dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember result = new dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember(this);
        result.appCode_ = appCode_;
        result.group_ = group_;
        result.action_ = action_;
        result.member_ = member_;
        result.owner_ = owner_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember) {
          return mergeFrom((dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember other) {
        if (other == dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember.getDefaultInstance()) return this;
        if (!other.getAppCode().isEmpty()) {
          appCode_ = other.appCode_;
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        if (!other.getMember().isEmpty()) {
          member_ = other.member_;
          onChanged();
        }
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appCode_ = "";
      /**
       * <code>string app_code = 1;</code>
       * @return The appCode.
       */
      public java.lang.String getAppCode() {
        java.lang.Object ref = appCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_code = 1;</code>
       * @return The bytes for appCode.
       */
      public com.google.protobuf.ByteString
          getAppCodeBytes() {
        java.lang.Object ref = appCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_code = 1;</code>
       * @param value The appCode to set.
       * @return This builder for chaining.
       */
      public Builder setAppCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppCode() {
        
        appCode_ = getDefaultInstance().getAppCode();
        onChanged();
        return this;
      }
      /**
       * <code>string app_code = 1;</code>
       * @param value The bytes for appCode to set.
       * @return This builder for chaining.
       */
      public Builder setAppCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 2;</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 2;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 2;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <code>string group = 2;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 3;</code>
       * @return The action.
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 3;</code>
       * @return The bytes for action.
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 3;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 3;</code>
       * @param value The bytes for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object member_ = "";
      /**
       * <code>string member = 4;</code>
       * @return The member.
       */
      public java.lang.String getMember() {
        java.lang.Object ref = member_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          member_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string member = 4;</code>
       * @return The bytes for member.
       */
      public com.google.protobuf.ByteString
          getMemberBytes() {
        java.lang.Object ref = member_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          member_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string member = 4;</code>
       * @param value The member to set.
       * @return This builder for chaining.
       */
      public Builder setMember(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        member_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string member = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMember() {
        
        member_ = getDefaultInstance().getMember();
        onChanged();
        return this;
      }
      /**
       * <code>string member = 4;</code>
       * @param value The bytes for member to set.
       * @return This builder for chaining.
       */
      public Builder setMemberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        member_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 5;</code>
       * @return The owner.
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 5;</code>
       * @return The bytes for owner.
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 5;</code>
       * @param value The owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 5;</code>
       * @param value The bytes for owner to set.
       * @return This builder for chaining.
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.MsgModifyGroupMember)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.MsgModifyGroupMember)
    private static final dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember();
    }

    public static dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgModifyGroupMember>
        PARSER = new com.google.protobuf.AbstractParser<MsgModifyGroupMember>() {
      @java.lang.Override
      public MsgModifyGroupMember parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgModifyGroupMember(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgModifyGroupMember> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgModifyGroupMember> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.MsgsGroupMember.MsgModifyGroupMember getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_MsgModifyGroupMember_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_MsgModifyGroupMember_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$dbchain/msgs/msgs_group_member.proto\022\014" +
      "dbchain.msgs\032\024gogoproto/gogo.proto\"f\n\024Ms" +
      "gModifyGroupMember\022\020\n\010app_code\030\001 \001(\t\022\r\n\005" +
      "group\030\002 \001(\t\022\016\n\006action\030\003 \001(\t\022\016\n\006member\030\004 " +
      "\001(\t\022\r\n\005owner\030\005 \001(\tB7Z5github.com/tharsis" +
      "/ethermint/x/dbchain/internal/typesb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_dbchain_msgs_MsgModifyGroupMember_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dbchain_msgs_MsgModifyGroupMember_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_MsgModifyGroupMember_descriptor,
        new java.lang.String[] { "AppCode", "Group", "Action", "Member", "Owner", });
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
