// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbchain/msgs/query.proto

package dbchain.msgs;

public final class QueryOuterClass {
  private QueryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryCheckChainIdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.QueryCheckChainIdRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code dbchain.msgs.QueryCheckChainIdRequest}
   */
  public static final class QueryCheckChainIdRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.QueryCheckChainIdRequest)
      QueryCheckChainIdRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryCheckChainIdRequest.newBuilder() to construct.
    private QueryCheckChainIdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryCheckChainIdRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryCheckChainIdRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryCheckChainIdRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest.class, dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest)) {
        return super.equals(obj);
      }
      dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest other = (dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dbchain.msgs.QueryCheckChainIdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.QueryCheckChainIdRequest)
        dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest.class, dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest.Builder.class);
      }

      // Construct using dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdRequest_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest getDefaultInstanceForType() {
        return dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest build() {
        dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest buildPartial() {
        dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest result = new dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest) {
          return mergeFrom((dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest other) {
        if (other == dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.QueryCheckChainIdRequest)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.QueryCheckChainIdRequest)
    private static final dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest();
    }

    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryCheckChainIdRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryCheckChainIdRequest>() {
      @java.lang.Override
      public QueryCheckChainIdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryCheckChainIdRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryCheckChainIdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryCheckChainIdRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.QueryOuterClass.QueryCheckChainIdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryCheckChainIdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbchain.msgs.QueryCheckChainIdResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code dbchain.msgs.QueryCheckChainIdResponse}
   */
  public static final class QueryCheckChainIdResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dbchain.msgs.QueryCheckChainIdResponse)
      QueryCheckChainIdResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryCheckChainIdResponse.newBuilder() to construct.
    private QueryCheckChainIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryCheckChainIdResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new QueryCheckChainIdResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryCheckChainIdResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse.class, dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse)) {
        return super.equals(obj);
      }
      dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse other = (dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dbchain.msgs.QueryCheckChainIdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbchain.msgs.QueryCheckChainIdResponse)
        dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse.class, dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse.Builder.class);
      }

      // Construct using dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbchain.msgs.QueryOuterClass.internal_static_dbchain_msgs_QueryCheckChainIdResponse_descriptor;
      }

      @java.lang.Override
      public dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse getDefaultInstanceForType() {
        return dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse build() {
        dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse buildPartial() {
        dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse result = new dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse) {
          return mergeFrom((dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse other) {
        if (other == dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dbchain.msgs.QueryCheckChainIdResponse)
    }

    // @@protoc_insertion_point(class_scope:dbchain.msgs.QueryCheckChainIdResponse)
    private static final dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse();
    }

    public static dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryCheckChainIdResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryCheckChainIdResponse>() {
      @java.lang.Override
      public QueryCheckChainIdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryCheckChainIdResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryCheckChainIdResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryCheckChainIdResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dbchain.msgs.QueryOuterClass.QueryCheckChainIdResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_QueryCheckChainIdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_QueryCheckChainIdRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbchain_msgs_QueryCheckChainIdResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dbchain_msgs_QueryCheckChainIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030dbchain/msgs/query.proto\022\014dbchain.msgs" +
      "\032\024gogoproto/gogo.proto\"\032\n\030QueryCheckChai" +
      "nIdRequest\"\033\n\031QueryCheckChainIdResponse2" +
      "o\n\005Query\022f\n\021QueryCheckChainId\022&.dbchain." +
      "msgs.QueryCheckChainIdRequest\032\'.dbchain." +
      "msgs.QueryCheckChainIdResponse\"\000B7Z5gith" +
      "ub.com/tharsis/ethermint/x/dbchain/inter" +
      "nal/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_dbchain_msgs_QueryCheckChainIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dbchain_msgs_QueryCheckChainIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_QueryCheckChainIdRequest_descriptor,
        new java.lang.String[] { });
    internal_static_dbchain_msgs_QueryCheckChainIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dbchain_msgs_QueryCheckChainIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dbchain_msgs_QueryCheckChainIdResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
